import { chat, parseJsonObject } from "@/lib/llm/client";
import {
  type ChecklistItem,
  type ChecklistSection,
  type ChecklistTemplateDoc,
  tierBResponseSchema,
} from "@/lib/checklist/schema";
import { isLlmConfigured } from "@/lib/env";

/**
 * Pipeline Tier B sesuai docs/prompt-generate-checklist-tier-b.md:
 * PASS 1 generate (temperature 0.3, JSON mode) → PASS 2 verifikasi skeptis
 * (temperature 0) → validasi schema di kode → dedup vs Tier A → normalisasi id
 * → status "beta".
 *
 * Semua langkah setelah PASS 2 dikerjakan di sini (bukan oleh LLM), karena
 * output mentah tidak boleh dipercaya.
 */

const MAX_ITEMS = 8;

const PASS1_SYSTEM = `You are an expert Indonesian used-car mechanic and inspector with deep, hands-on
knowledge of common model-specific problems ("penyakit mobil") in the Indonesian
used-car market.

Your task: produce a list of WELL-DOCUMENTED, MODEL-SPECIFIC issues for a given
car (brand, model, year range). These are problems that are widely known among
Indonesian mechanics, owner communities, and specialist workshops for THIS
specific model/generation — NOT generic used-car issues.

STRICT RULES:
- Output ONLY issues that are genuinely well-known and documented for this exact
  model/generation. If you are not confident an issue is real and common for THIS
  model, DO NOT include it. It is far better to return fewer, correct items than
  more items with fabricated ones.
- DO NOT include generic checks that apply to all cars (e.g. "check for flood
  damage", "check brakes", "check documents"). Those are handled separately.
  Only include issues that are characteristic of THIS model.
- Return at most ${MAX_ITEMS} items.
- For each issue, set "confidence":
    - "high"   = a classic, widely-cited problem for this model.
    - "medium" = plausible and reported, but less universal.
  DO NOT output anything below "medium". If unsure, omit it.
- In "catatan_verifikasi", briefly state WHY this is a known issue for this model
  (the mechanism / where it's commonly discussed). One sentence.
- ALL content values (label, cara_cek, tanda_bahaya, estimasi_biaya_perbaikan,
  catatan_verifikasi) MUST be written in Bahasa Indonesia, plain language for a
  layperson buyer.
- "cara_cek" must be a concrete step a non-expert can do during a viewing.
- Estimasi biaya in rough Rupiah ranges realistic for Indonesia, written as a
  range like "Rp 500rb - 3jt" so it can be parsed.
- For "input_type": use "boolean" only for a yes/no fact, and then you MUST set
  "polaritas" to "ya_aman" (yes means the car is fine) or "ya_bahaya" (yes means
  a problem was found). Otherwise use "scale".
- Output MUST be valid JSON matching the schema below. No prose, no markdown.

OUTPUT SCHEMA:
{
  "brand": "string",
  "model": "string",
  "year_range": "string",
  "tier": "B",
  "items": [
    {
      "id": "snake_case_unique_id",
      "label": "string",
      "cara_cek": "string",
      "tanda_bahaya": "string",
      "severity": "major | minor | addon",
      "input_type": "boolean | scale | text | photo",
      "polaritas": "ya_aman | ya_bahaya",
      "wajib_foto": boolean,
      "estimasi_biaya_perbaikan": "string",
      "status": "beta",
      "confidence": "high | medium",
      "catatan_verifikasi": "string"
    }
  ]
}

If you genuinely know of no well-documented model-specific issues, return an empty
"items" array. An empty list is an acceptable and honest answer.`;

const PASS2_SYSTEM = `You are a highly skeptical senior vehicle-inspection reviewer. You are auditing a
list of claimed model-specific issues generated by another system, which is known
to sometimes hallucinate problems that are not actually characteristic of the
model.

Your job is to REMOVE any item that is not a genuinely well-documented,
model-specific issue for the exact car given. Be strict. When in doubt, REMOVE.

For each item in the input, evaluate:
1. Is this a REAL, commonly-known issue specifically for THIS model/generation
   (not a generic used-car issue, not invented)?
2. Is "cara_cek" something a layperson can actually do during a viewing?
3. Is the severity and cost estimate reasonable?

Actions:
- Remove any item that is generic (applies to all cars), fabricated, dubious, or
  that you cannot reasonably confirm as a known issue for this model.
- Remove any item whose "confidence" is not justified; you may downgrade "high" to
  "medium" but never upgrade.
- Keep only items you are confident are legitimate model-specific issues.
- Do NOT add new items. Do NOT rewrite content beyond minor clarity fixes.

Output MUST be valid JSON in the SAME schema as the input. No prose, no markdown.
It is acceptable and often correct to return a shorter list, or an empty "items"
array if nothing survives scrutiny. All content stays in Bahasa Indonesia.`;

/** Topik yang sudah dicakup Tier A — item Tier B dengan makna sama dibuang. */
const TOPIK_TIER_A = [
  ["banjir", "lumpur", "garis air"],
  ["tabrak", "las", "dempul", "celah panel", "rangka"],
  ["dokumen", "bpkb", "stnk", "nomor rangka", "nomor mesin", "pajak", "blokir"],
  ["odometer", "km diputar", "kilometer"],
  ["rem blong", "kampas rem"],
  ["oli bercampur air", "emulsi"],
  ["asap knalpot"],
  ["ban tipis", "tahun ban"],
];

function normalizeText(value: string): string {
  return value.toLowerCase().replace(/\s+/g, " ").trim();
}

function duplikatTierA(item: ChecklistItem, tierAItems: ChecklistItem[]): boolean {
  const haystack = normalizeText(`${item.label} ${item.tanda_bahaya}`);

  for (const grup of TOPIK_TIER_A) {
    const cocok = grup.filter((kata) => haystack.includes(kata)).length;
    if (cocok > 0 && grup.some((kata) => normalizeText(item.label).includes(kata))) {
      return true;
    }
  }

  return tierAItems.some((tierA) => {
    const a = new Set(normalizeText(tierA.label).split(" ").filter((w) => w.length > 3));
    const b = normalizeText(item.label)
      .split(" ")
      .filter((word) => word.length > 3);
    if (a.size === 0 || b.length === 0) return false;
    const overlap = b.filter((word) => a.has(word)).length;
    return overlap / b.length >= 0.6;
  });
}

function slug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/(^_|_$)/g, "")
    .slice(0, 24);
}

export type TierBOutcome =
  | { status: "done"; section: ChecklistSection; dibuang: number }
  | { status: "skipped"; reason: string }
  | { status: "failed"; reason: string };

export async function generateTierBSection(input: {
  brand: string;
  model: string;
  yearRange: string;
  variant?: string | null;
  tierAItems: ChecklistItem[];
}): Promise<TierBOutcome> {
  if (!isLlmConfigured()) {
    return { status: "skipped", reason: "LLM belum dikonfigurasi" };
  }

  const kendaraan = `${input.brand} ${input.model} ${input.yearRange}`;

  try {
    const pass1Raw = await chat(
      [
        { role: "system", content: PASS1_SYSTEM },
        {
          role: "user",
          content: `Kendaraan:
- Brand: ${input.brand}
- Model: ${input.model}
- Year range: ${input.yearRange}
- Varian/mesin (opsional): ${input.variant || "-"}

Hasilkan daftar penyakit spesifik model ini sesuai aturan.`,
        },
      ],
      { temperature: 0.3, json: true, maxTokens: 2_500 },
    );

    const pass2Raw = await chat(
      [
        { role: "system", content: PASS2_SYSTEM },
        {
          role: "user",
          content: `Kendaraan: ${kendaraan}

Daftar item yang harus diaudit (JSON dari tahap sebelumnya):
${pass1Raw}

Audit dan kembalikan hanya item yang lolos, dalam schema yang sama.`,
        },
      ],
      { temperature: 0, json: true, maxTokens: 2_500 },
    );

    const parsed = tierBResponseSchema.safeParse(parseJsonObject(pass2Raw));
    if (!parsed.success) {
      return {
        status: "failed",
        reason: `Output tidak sesuai schema: ${parsed.error.issues[0]?.message ?? "tidak diketahui"}`,
      };
    }

    const seen = new Set<string>();
    const kandidat = parsed.data.items.slice(0, MAX_ITEMS);
    const lolos: ChecklistItem[] = [];
    let dibuang = 0;

    for (const raw of kandidat) {
      const item: ChecklistItem = {
        ...raw,
        // id di-prefix supaya tidak pernah bentrok dengan id Tier A
        id: `b_${slug(input.model)}_${slug(raw.id)}`,
        status: "active",
        tier: "B",
        wajib_foto: raw.wajib_foto ?? false,
        polaritas:
          raw.input_type === "boolean" ? (raw.polaritas ?? "ya_bahaya") : raw.polaritas,
      };

      if (seen.has(item.id) || duplikatTierA(item, input.tierAItems)) {
        dibuang += 1;
        continue;
      }
      seen.add(item.id);
      // Item "medium" tetap disimpan tapi masuk optional (collapsed) sampai
      // divalidasi feedback user — lihat prompt pack §5.
      lolos.push(item.confidence === "medium" ? { ...item, status: "optional" } : item);
    }

    if (lolos.length === 0) {
      return { status: "skipped", reason: "Tidak ada item yang lolos verifikasi" };
    }

    return {
      status: "done",
      dibuang,
      section: {
        severity: "major",
        title: `Penyakit Khas ${input.model} (Beta)`,
        deskripsi:
          "Bagian ini belum terverifikasi. Isinya disusun oleh AI dan sedang diperbaiki dari masukan pengguna, jadi perlakukan sebagai petunjuk awal, bukan fakta.",
        tier: "B",
        beta: true,
        items: lolos,
      },
    };
  } catch (error) {
    return {
      status: "failed",
      reason: error instanceof Error ? error.message : "Gagal menghubungi LLM",
    };
  }
}

export function tierAItemsOf(template: ChecklistTemplateDoc): ChecklistItem[] {
  return template.sections
    .filter((section) => section.tier !== "B")
    .flatMap((section) => section.items);
}
